---
sudo: false
dist: trusty
language: node_js
node_js:
  - '8.3'
  - '8'

cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@$(node -p "require('./package').engines.npm")
  - touch package.json

install:
  - make install

script:
  - make lint
  - make test

after_success:
  - make coverage
  - cat coverage/lcov.info | node_modules/.bin/coveralls

env:
  global:
    secure: KAfoKO+HsU18FwyAfOlKrqC0rfPdPQwaeibr0YnUqW2EmvFOGiuD6go4iFjLKEIc4V19k1JVdJX8p8Lqo5sDH/CqSDFoaKkxqFWfvgsfSiNrfMpVyFBSOPpSWtAfB7Y2+v4EHEtDiTMBjuWTz7ueSU+vtgei0abgeqwax2BFOTNvzczfe/yC5EfHCKIgwuojV0Ya1aNo5E5ZCx23/sqhWEjBBE+3nFUxsCgxuAgG3YlkFxDXIHzsmz+WDdYWcf5RJJTGfW35Tzqu8g0XA0VaiFLtySoXT+q7LpWyI6okU3T88JV8PDldZEZORICj7YrHzDwPb5yG8sCO7IJWZ8UlLhUww2BUIEFWpaB3q/FqIZuVeeIfwZ+JKko31FXQ9e9VtbxPwePeYc1wu8tYM5KUvLKEJ/UQNPJY63T+D2Tu84wNKTMAn/1JbIXlMolFhVvpNIU8AKMebt+R2UfPddu5hAbKdcB/lTSGKffRtO+WxwikPIrbKR0xBM25cWFt6yhLTHcVspomT9ZgR5tt/T1IW7fVGi/Vjqv8vmJc7pqakn1Pca1RuWXlDLt3ppyPdaI1+e3PKHL72h2wheJBEMs5vkFjFOphcspVbQ8+y41X0OIHyt2DCp6U5wImraKdtBd14o4rOkzfLmSC9bKY3oWZIIVI8AbU4H3RWzC84KGdgeY=

deploy:
  skip_cleanup: true
  provider: script
  script: ci/travis-release.sh
  on:
    branch: release
    node_js: '8'
